"""update_table_email_history

Revision ID: 171b4bf6f742
Revises: d553f8da762c
Create Date: 2024-08-28 10:28:01.873395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '171b4bf6f742'
down_revision = 'd553f8da762c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_histories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_recipients', sa.Text(), nullable=True))
        batch_op.drop_column('user_recipients')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_histories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_recipients', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('email_recipients')

    # ### end Alembic commands ###
