"""update_table_email

Revision ID: d553f8da762c
Revises: 3ebc3bbbbe2c
Create Date: 2024-08-27 17:02:49.465664

"""
from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision = 'd553f8da762c'
down_revision = '3ebc3bbbbe2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_histories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_recipients', sa.Text(), nullable=True))
        batch_op.drop_constraint('email_histories_user_recipient_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_recipient_id')

    op.sync_enum_values('public', 'email_status_choices_enum', ['PENDING', 'PROCESS', 'SUCCESS', 'FAILED'],
                        [TableReference(table_schema='public', table_name='emails', column_name='status')],
                        enum_values_to_rename=[])
    op.sync_enum_values('public', 'email_history_status_choices_enum', ['PENDING', 'PROCESS', 'SUCCESS', 'FAILED'],
                        [TableReference(table_schema='public', table_name='email_histories', column_name='status')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'email_history_status_choices_enum', ['PENDING', 'QUEUED', 'SUCCESS', 'FAIL'],
                        [TableReference(table_schema='public', table_name='email_histories', column_name='status')],
                        enum_values_to_rename=[])
    op.sync_enum_values('public', 'email_status_choices_enum', ['PENDING', 'QUEUED', 'SUCCESS', 'FAIL'],
                        [TableReference(table_schema='public', table_name='emails', column_name='status')],
                        enum_values_to_rename=[])
    with op.batch_alter_table('email_histories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_recipient_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('email_histories_user_recipient_id_fkey', 'user_recipients', ['user_recipient_id'], ['id'])
        batch_op.drop_column('user_recipients')

    # ### end Alembic commands ###
