"""remove_is_delete

Revision ID: e01cb3f965d5
Revises: 171b4bf6f742
Create Date: 2024-08-28 19:55:50.336185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e01cb3f965d5'
down_revision = '171b4bf6f742'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_histories', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('user_recipients', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_recipients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))

    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))

    with op.batch_alter_table('email_histories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
